### ISSUE TITLE
贴子底部的广告能去吗

### ISSUE THREAD

**Issue by xushet** [chr233/PureNGA#1]
![Screenshot_20230212-014824_NGA玩家社区.png](https://user-images.githubusercontent.com/34502902/218273106-e97368ea-e716-4a88-9920-1b3983de5db6.png)

nga版本9.5.6

**Comment by xushet** [comment]
还有贴子列表插入的广告
![IMG_20230212_015423.png](https://user-images.githubusercontent.com/34502902/218273310-7cd18586-c37d-43b5-a5c4-db8c8621ad6c.png)

**Comment by chr233** [comment]
每日任务那里有个去广告任务，那个做了Hook，点进去直接关闭广告就可以完成任务，做一次可以24小时免广告

**Comment by TianXiaSky** [comment]
> 每日任务那里有个去广告任务，那个做了Hook，点进去直接关闭广告就可以完成任务，做一次可以24小时免广告

大佬，N币的任务好像不能像广告任务一样直接退出就完成，是不是两种任务是不一样的

**Comment by chr233** [comment]
是的，这是一个已知的问题，有待修复

**Comment by TianXiaSky** [comment]
> 是的，这是一个已知的问题，有待修复

原来是这样，好的了解

**Comment by chr233** [comment]
1.4.0已更新，可以去掉内嵌广告了
