### ISSUE TITLE
独立插件版在 NGA 9.9.9 报错

### ISSUE THREAD

**Issue by 1nj0k** [chr233/PureNGA#10]
显示“模块 OptimizeHook 加载出现未知错误”，附上log
[file_9118557894951037973.zip](https://github.com/chr233/PureNGA/files/14973508/file_9118557894951037973.zip)

**Comment by chr233** [comment]
更新nga，或者降级插件

**Comment by chr233** [comment]
禁用 屏蔽日历弹窗 这个选项就行了，旧版本NGA没有CalendarUtils这个类，这个逻辑报错了

**Comment by chr233** [comment]
用 2.4.1，优化了旧版本的兼容问题
