### ISSUE TITLE
9.9.30 NGA 帖子中间的广告无法去除

### ISSUE THREAD

**Issue by sakana164** [chr233/PureNGA#11]
![Screenshot_2024-06-10-13-29-25-475_gov pianzong androidnga](https://github.com/chr233/PureNGA/assets/76257039/fc7e40d6-3c93-45a7-bbde-2d691c3c3683)

NGA版本号9.9.30，用的是模块版，框架LSPosed，模块设置如下

![Screenshot_2024-06-10-13-30-21-563_gov pianzong androidnga](https://github.com/chr233/PureNGA/assets/76257039/544f070b-0753-4685-b85a-9a858cfd98c3)

**Comment by chr233** [comment]
模块是最新的吗

**Comment by chr233** [comment]
看到了，客户端退上个版本吧，123网盘里有历史版本

**Comment by chr233** [comment]
修不好，近期没法更新

**Comment by sakana164** [comment]
> 修不好，近期没法更新

那不急😂

**Comment by chr233** [comment]
2.5.0 已适配

**Comment by sakana164** [comment]
> 2.5.0 已适配

好耶😘

**Comment by chr233** [comment]
好像还有2个SDK的广告有概率会显示

**Comment by sakana164** [comment]
> 好像还有2个SDK的广告有概率会显示

我发现了，我以为是我没清缓存

**Comment by chr233** [comment]
有的时候又刷不到，很奇怪

**Comment by sakana164** [comment]
> 有的时候又刷不到，很奇怪

![Screenshot_2024-06-12-14-02-17-809_gov.pianzong.androidnga.jpg](https://github.com/chr233/PureNGA/assets/76257039/25554f88-71fb-4905-9206-c0c57dbc4bbe)

是这样的，有时候有，有时候没有😂

**Comment by chr233** [comment]
[app-release.zip](https://github.com/user-attachments/files/15800131/app-release.zip)

试试这个版本，看看还有没有广告

**Comment by sakana164** [comment]
> [app-release.zip](https://github.com/user-attachments/files/15800131/app-release.zip)
> 
> 试试这个版本，看看还有没有广告

还是有
![Screenshot_2024-06-12-15-26-37-545_gov.pianzong.androidnga.jpg](https://github.com/chr233/PureNGA/assets/76257039/5258b5c9-36db-4adb-b604-017bed33fa7b)

**Comment by chr233** [comment]
我的账号已经刷不出来广告了……

**Comment by sakana164** [comment]
> 我的账号已经刷不出来广告了……

我还是有😂
![Screenshot_2024-06-12-15-35-51-137_gov.pianzong.androidnga.jpg](https://github.com/chr233/PureNGA/assets/76257039/bcd46d15-c75e-41c0-abf9-ae50e9d976d9)

难道有啥激励机制？看多了广告就不显示了？

**Comment by chr233** [comment]
不知道，我换了两个账号都不显示广告了

**Comment by sakana164** [comment]
> 不知道，我换了两个账号都不显示广告了

我基本上稳定出现🤣，这有log抓么

**Comment by chr233** [comment]
好像跟手机有关，换了个手机偶尔会有

**Comment by chr233** [comment]
除了taptap的广告还会有其他类型的广告出现吗

**Comment by sakana164** [comment]
> 除了taptap的广告还会有其他类型的广告出现吗

![Screenshot_2024-06-12-16-01-49-994_gov.pianzong.androidnga.jpg](https://github.com/chr233/PureNGA/assets/76257039/43879265-ed1d-4a92-9264-42c792fc5d30)

![Screenshot_2024-06-12-16-02-05-642_gov.pianzong.androidnga.jpg](https://github.com/chr233/PureNGA/assets/76257039/20a0921a-e26d-4392-92cf-bb08952b1ceb)

![Screenshot_2024-06-12-16-02-30-797_gov.pianzong.androidnga.jpg](https://github.com/chr233/PureNGA/assets/76257039/1cd52c51-eff6-4241-bd0a-f18092ef541e)


![Screenshot_2024-06-12-16-02-41-500_gov.pianzong.androidnga.jpg](https://github.com/chr233/PureNGA/assets/76257039/312abdfe-35f5-41e0-a033-0e2c851f0a92)

有的看不出来是谁的广告🧐

**Comment by chr233** [comment]
[app-release.zip](https://github.com/user-attachments/files/15800902/app-release.zip)

都是taptap

**Comment by sakana164** [comment]
> [app-release.zip](https://github.com/user-attachments/files/15800902/app-release.zip)
> 
> 都是taptap

好了，广告都没了，没问题了🤩
