### ISSUE TITLE
模块 WebViewHook 加载遇到未知错误

### ISSUE THREAD

**Issue by LynahZ** [chr233/PureNGA#12]
RT
NGA 9.9.32
PureNGA 2.5.1

**Comment by chr233** [comment]
退回9.9.31即可，最近比较忙，暂时没有更新的计划

或者可以去插件设置里打开静默报错信息

**Comment by chr233** [comment]
修了，只是有证书的电脑不在身边，没条件发版，禁用 屏蔽内置浏览器 可以避免这个提示

**Comment by LynahZ** [comment]
> 修了，只是有证书的电脑不在身边，没条件发版，禁用 屏蔽内置浏览器 可以避免这个提示

辛苦了！
