### ISSUE TITLE
2.6.1版本打开论坛版面时，帖子列表是空的

### ISSUE THREAD

**Issue by aeneask** [chr233/PureNGA#13]
试了两个都不行，就回退到2.6.0了

**Comment by chr233** [comment]
是不是设置了屏蔽帖子

**Comment by chr233** [comment]
应该是屏蔽帖子的逻辑有问题，设置一下屏蔽词就行了

**Comment by aeneask** [comment]
> 应该是屏蔽帖子的逻辑有问题，设置一下屏蔽词就行了

是的，如果打开了“屏蔽广告帖子”就有问题，但随便设置了屏蔽词就没问题；或者不打开“屏蔽广告帖子”也没问题

**Comment by chr233** [comment]
2.7.1修了

**Comment by aeneask** [comment]
> 2.7.1修了

确实解决了，谢谢
