### ISSUE TITLE
无论我打开还是关闭用外部浏览器打开链接点图片等超链接都提示我选择浏览器

### ISSUE THREAD

**Issue by seraph758** [chr233/PureNGA#14]
以前没有问题，自从有了这个功能之后，我打开了一次。以后再打开关闭都提示我选择浏览器

**Comment by chr233** [comment]
有没有帖子链接给个，我测试下

**Comment by chr233** [comment]
禁用后需要重启app才能生效

**Comment by seraph758** [comment]
Nga 9.9.36
插件版本 2。9
https://ngabbs.com/read.php?tid=41755024

基本上所有的超链接都提示选择浏览器，不管是图片还是点回复都让选择浏览器
![Screenshot_2024-09-23-19-19-35-92_3583b5560b9060cb28008c20a0fd6fa9](https://github.com/user-attachments/assets/d5c2bd58-e9a2-4f99-8fe9-8bc1c9e2f7c4)
![Screenshot_2024-09-23-19-19-45-91_c31b32364ce19ca8fcd150a417ecce58](https://github.com/user-attachments/assets/abebf9a6-f5f5-4410-902a-5121d886c1f5)

![Screenshot_2024-09-23-19-18-10-77_3583b5560b9060cb28008c20a0fd6fa9](https://github.com/user-attachments/assets/1f24b2c2-536b-47a8-ac0d-e331c23d461c)

**Comment by chr233** [comment]
https://github.com/user-attachments/assets/30bdbdd9-83a1-4c74-adc8-b1ea53170686

我这好像没问题

**Comment by seraph758** [comment]
是我手机的问题，把模块关了也是这样。换了个手机都正常

**Comment by chr233** [comment]
> 是我手机的问题，把模块关了也是这样。换了个手机都正常

什么手机

**Comment by seraph758** [comment]
> > 是我手机的问题，把模块关了也是这样。换了个手机都正常
> 
> 什么手机

一加12，刷的氧
我用备用机一加9pro，装同一个nga. App 就正常

**Comment by chr233** [comment]
> 在酷安问了一嘴，有人说是130的webview 有问题，我卸载更新后，果然解决了

这个功能的逻辑调用的是原版app实现的，应该是原版不兼容130

**Comment by chr233** [comment]
> > 在酷安问了一嘴，有人说是130的webview 有问题，我卸载更新后，果然解决了
> 
> 这个功能的逻辑调用的是原版app实现的，应该是原版不兼容130

建议去论坛反馈，不要提到插件就行了

**Comment by seraph758** [comment]
> > > 在酷安问了一个嘴，有人说是130的webview有问题，我卸载更新后，终于解决了
> > 
> > 
> > 这个功能的逻辑调用的是原版app实现的，应该是原版不兼容130
> 
> 建议去论坛反馈，不要提到插件就行了

我在论坛找了好久，不知道哪个板块能反馈……

**Comment by chr233** [comment]
9.9.38 已经修正这个问题了，更新客户端即可

**Comment by DBY2-W00** [comment]
> 9.9.38 已经修正这个问题了，更新客户端即可

我也是，昨天还好好的，什么也没动，今天就遇到这个问题了，升级了一下也不管用。
用的小米k70，HyperOS 1.0.19
![Screenshot_2024-10-24-11-28-16-329_android](https://github.com/user-attachments/assets/8b4f170f-fb0b-4166-8469-950f7110761e)
![Screenshot_2024-10-24-11-28-24-851_gov pianzong androidnga](https://github.com/user-attachments/assets/fcfc3b11-b77d-4742-87ca-2c780ad8cc72)

**Comment by chr233** [comment]
> > 9.9.38 已经修正这个问题了，更新客户端即可
> 
> 我也是，昨天还好好的，什么也没动，今天就遇到这个问题了，图片和链接都弹下面的窗口，外部链接那个选项关闭了，升级了一下客户端也不管用。 用的小米k70，HyperOS 1.0.19 ![Screenshot_2024-10-24-11-28-16-329_android](https://private-user-images.githubusercontent.com/16357305/379533890-8b4f170f-fb0b-4166-8469-950f7110761e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3NDgxNTQsIm5iZiI6MTcyOTc0Nzg1NCwicGF0aCI6Ii8xNjM1NzMwNS8zNzk1MzM4OTAtOGI0ZjE3MGYtZmIwYi00MTY2LTg0NjktOTUwZjcxMTA3NjFlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI0VDA1MzA1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxNzQxMGFlNTM3OWE0NDAwNmFiYThlNmY0ZTgxZGM5ZGQzOGQwNmI4Mjg1MGFiMDRhMTg5MGNjZGE3OWYzYmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.diDwZoUqlpdNAgjY50_8fSicYfoXMaE6w0tRATzo9e8) ![Screenshot_2024-10-24-11-28-24-851_gov pianzong androidnga](https://private-user-images.githubusercontent.com/16357305/379533916-fcfc3b11-b77d-4742-87ca-2c780ad8cc72.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3NDgxNTQsIm5iZiI6MTcyOTc0Nzg1NCwicGF0aCI6Ii8xNjM1NzMwNS8zNzk1MzM5MTYtZmNmYzNiMTEtYjc3ZC00NzQyLTg3Y2EtMmM3ODBhZDhjYzcyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI0VDA1MzA1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiNjJlYTZjNWMzYjNmZTJkZjVjYTJiNTc0Mzk1ZmFmMGQxOWI3M2I2ZjFkZTE5ODE2MTc1NjI5NWM2YjExYjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VGNi6uLWXOOq0UP_M4rdsnYKoRsFp1ewl0JXoLZxvBU)

原版app的问题，好像没完全修好 webview 130 以上版本的兼容性问题，去论坛反馈一下，或者降级webview版本
