### ISSUE TITLE
可以去掉这个提示吗

### ISSUE THREAD

**Issue by twcgzgs** [chr233/PureNGA#15]
画圈那个广告提示![Screenshot_2024-10-12-20-12-19-657_gov.pianzong.androidnga-edit.jpg](https://github.com/user-attachments/assets/63411cee-ae66-4e2f-93e2-0fd91eab9dc0)

**Comment by chr233** [comment]
不太好做，主要存在感不强，没什么必要去掉

**Comment by twcgzgs** [comment]
> 不太好做，主要存在感不强，没什么必要去掉

ok
