### ISSUE TITLE
查看楼中楼的回复或楼层的图片附件时，会自动跳转至浏览器

### ISSUE THREAD

**Issue by dyskyside** [chr233/PureNGA#16]
之前使用正常，近两天才突发这个问题，以前查看楼中楼的回复会直接显示内容，查看图片类型的附件会直接显示图片，现在则会直接跳转至浏览器
![Screenshot_20241109-003823](https://github.com/user-attachments/assets/5842c250-6d7b-4038-a587-1251930bc330)

**Comment by chr233** [comment]
降级 webview 到130以前的版本就行了
![Screenshot_2024-11-09-10-52-44-615_com.miui.securitycenter.jpg](https://github.com/user-attachments/assets/195b2f8c-f2fe-4c01-99a5-622f516ca9db)

**Comment by dyskyside** [comment]
> 降级 webview 到130以前的版本就行了 ![Screenshot_2024-11-09-10-52-44-615_com.miui.securitycenter.jpg](https://private-user-images.githubusercontent.com/13798576/384570778-195b2f8c-f2fe-4c01-99a5-622f516ca9db.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExMzI2NDYsIm5iZiI6MTczMTEzMjM0NiwicGF0aCI6Ii8xMzc5ODU3Ni8zODQ1NzA3NzgtMTk1YjJmOGMtZjJmZS00YzAxLTk5YTUtNjIyZjUxNmNhOWRiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA5VDA2MDU0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2ZTJhNWYwM2Q4OWY1NmVkNjI3ZGVmNzJhZmQ3ZDUzYjUyYTJkZjc1MzkyNDA2MTc0Y2MwMzA1Y2E5YWVhMDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hoEtGQP_VbOJr9MUezA-UI5iakDTjCZAwc93u-IKMHY)

谢谢解答
