### ISSUE TITLE
闪退、自动重启比较多

### ISSUE THREAD

**Issue by aeneask** [chr233/PureNGA#3]
在用nga_9.8.5-1.10.0-lspatched版本，1.10版本的其他9.8.x也都是如此

**Comment by chr233** [comment]
安卓版本号多少，安卓9以前的系统可能兼容性不佳

**Comment by chr233** [comment]
或者尝试自己下载 lstapch 进行打包

**Comment by aeneask** [comment]
> 安卓版本号多少，安卓9以前的系统可能兼容性不佳

华为mate40，鸿蒙4

**Comment by chr233** [comment]
> > 安卓版本号多少，安卓9以前的系统可能兼容性不佳
> 
> 华为mate40，鸿蒙4

其他版本有这个问题吗，可以试试9.7.x，9.6.x的版本？

**Comment by aeneask** [comment]
> > > 安卓版本号多少，安卓9以前的系统可能兼容性不佳
> > 
> > 
> > 华为mate40，鸿蒙4
> 
> 其他版本有这个问题吗，可以试试9.7.x，9.6.x的版本？

试了9.7.8似乎比较稳定，没有崩溃并自动重启。不知道1.11能否适配9.7.x版本？

**Comment by chr233** [comment]
> > > > 安卓版本号多少，安卓9以前的系统可能兼容性不佳
> > > 
> > > 
> > > 华为mate40，鸿蒙4
> > 
> > 
> > 其他版本有这个问题吗，可以试试9.7.x，9.6.x的版本？
> 
> 试了9.7.8似乎比较稳定，没有崩溃并自动重启。不知道1.11能否适配9.7.x版本？

可以的，可以使用 [Lapatch](https://github.com/LSPosed/LSPatch/releases/latest) 自行打包，lspatch.jar 是命令行工具，另一个可以在手机运行

**Comment by chr233** [comment]
可能跟UI框架有关，帮你打包一个 9.8.6 x 1.6.0 的版本，方便的话试试会不会闪退

https://www.123pan.com/s/qYTvjv-3mutv.html提取码:q4NF

手头上的设备没有遇到过闪退的情况，鸿蒙可能对lspatch兼容性有问题

**Comment by aeneask** [comment]
> 可能跟UI框架有关，帮你打包一个 9.8.6 x 1.6.0 的版本，方便的话试试会不会闪退
> 
> [https://www.123pan.com/s/qYTvjv-3mutv.html提取码:q4NF](https://www.123pan.com/s/qYTvjv-3mutv.html%E6%8F%90%E5%8F%96%E7%A0%81:q4NF)
> 
> 手头上的设备没有遇到过闪退的情况，鸿蒙可能对lspatch兼容性有问题
谢谢，不过1.6.0界面没去掉活动页面、商城页面，看起来不爽。

意外发现nga_9.8.0-1.10.0-lspatched.apk版本也不会闪退并自动重启，其他9.8.x版本不管是1.10还是1.11都会闪退重启。

另外，能否启动后，自动跳到社区页面，而不是首页？

**Comment by chr233** [comment]
> > 可能跟UI框架有关，帮你打包一个 9.8.6 x 1.6.0 的版本，方便的话试试会不会闪退
> > [https://www.123pan.com/s/qYTvjv-3mutv.html提取码:q4NF](https://www.123pan.com/s/qYTvjv-3mutv.html%E6%8F%90%E5%8F%96%E7%A0%81:q4NF)
> > 手头上的设备没有遇到过闪退的情况，鸿蒙可能对lspatch兼容性有问题
> > 谢谢，不过1.6.0界面没去掉活动页面、商城页面，看起来不爽。
> 
> 意外发现nga_9.8.0-1.10.0-lspatched.apk版本也不会闪退并自动重启，其他9.8.x版本不管是1.10还是1.11都会闪退重启。
> 
> 另外，能否启动后，自动跳到社区页面，而不是首页？

跳转社区可以做，闪退原因未知，大概率跟hook框架有关，没有设备调试、定位问题

**Comment by aeneask** [comment]
> > > 可能跟UI框架有关，帮你打包一个 9.8.6 x 1.6.0 的版本，方便的话试试会不会闪退
> > > [https://www.123pan.com/s/qYTvjv-3mutv.html提取码:q4NF](https://www.123pan.com/s/qYTvjv-3mutv.html%E6%8F%90%E5%8F%96%E7%A0%81:q4NF)
> > > 手头上的设备没有遇到过闪退的情况，鸿蒙可能对lspatch兼容性有问题
> > > 谢谢，不过1.6.0界面没去掉活动页面、商城页面，看起来不爽。
> > 
> > 
> > 意外发现nga_9.8.0-1.10.0-lspatched.apk版本也不会闪退并自动重启，其他9.8.x版本不管是1.10还是1.11都会闪退重启。
> > 另外，能否启动后，自动跳到社区页面，而不是首页？
> 
> 跳转社区可以做，闪退原因未知，大概率跟hook框架有关，没有设备调试、定位问题

nga_9.8.0-1.10.0-lspatched.apk，刷论坛半个小时到一个小时（没有严格计时），才会闪崩并重启一次，感觉在容忍范围内了。其他9.8.x的，感觉十来分钟就得崩一次并自动重启app

**Comment by chr233** [comment]
> 为了测试情况，今天疯狂更换版本、刷论坛。。。

感觉应该是新版本插件用到了一些过时的安卓方法，可能鸿蒙没有提供导致的报错，主要没有设备没法调试

**Comment by chr233** [comment]
https://github.com/LSPosed/LSPatch/issues/104#issuecomment-1250909963

可能类似的问题？

**Comment by chr233** [comment]
> > > > 可能跟UI框架有关，帮你打包一个 9.8.6 x 1.6.0 的版本，方便的话试试会不会闪退
> > > > [https://www.123pan.com/s/qYTvjv-3mutv.html提取码:q4NF](https://www.123pan.com/s/qYTvjv-3mutv.html%E6%8F%90%E5%8F%96%E7%A0%81:q4NF)
> > > > 手头上的设备没有遇到过闪退的情况，鸿蒙可能对lspatch兼容性有问题
> > > > 谢谢，不过1.6.0界面没去掉活动页面、商城页面，看起来不爽。
> > > 
> > > 
> > > 意外发现nga_9.8.0-1.10.0-lspatched.apk版本也不会闪退并自动重启，其他9.8.x版本不管是1.10还是1.11都会闪退重启。
> > > 另外，能否启动后，自动跳到社区页面，而不是首页？
> > 
> > 
> > 跳转社区可以做，闪退原因未知，大概率跟hook框架有关，没有设备调试、定位问题
> 
> nga_9.8.0-1.10.0-lspatched.apk，刷论坛半个小时到一个小时（没有严格计时），才会闪崩并重启一次，感觉在容忍范围内了。其他9.8.x的，感觉十来分钟就得崩一次并自动重启app

插件功能开了哪些，没开哪些，还是都没打开？

**Comment by aeneask** [comment]
> > > > > 可能跟UI框架有关，帮你打包一个 9.8.6 x 1.6.0 的版本，方便的话试试会不会闪退
> > > > > [https://www.123pan.com/s/qYTvjv-3mutv.html提取码:q4NF](https://www.123pan.com/s/qYTvjv-3mutv.html%E6%8F%90%E5%8F%96%E7%A0%81:q4NF)
> > > > > 手头上的设备没有遇到过闪退的情况，鸿蒙可能对lspatch兼容性有问题
> > > > > 谢谢，不过1.6.0界面没去掉活动页面、商城页面，看起来不爽。
> > > > 
> > > > 
> > > > 意外发现nga_9.8.0-1.10.0-lspatched.apk版本也不会闪退并自动重启，其他9.8.x版本不管是1.10还是1.11都会闪退重启。
> > > > 另外，能否启动后，自动跳到社区页面，而不是首页？
> > > 
> > > 
> > > 跳转社区可以做，闪退原因未知，大概率跟hook框架有关，没有设备调试、定位问题
> > 
> > 
> > nga_9.8.0-1.10.0-lspatched.apk，刷论坛半个小时到一个小时（没有严格计时），才会闪崩并重启一次，感觉在容忍范围内了。其他9.8.x的，感觉十来分钟就得崩一次并自动重启app
> 
> 插件功能开了哪些，没开哪些，还是都没打开？

全都打开了。

用了一天nga_9.8.7-1.11.0-lspatched.apk，没有闪崩并自动重启过，我感觉这个issue可以close了，哈哈

**Comment by aeneask** [comment]
刚说完，就崩了一次。。。是在下拉刷新版面时

**Comment by chr233** [comment]
> 刚说完，就崩了一次。。。是在下拉刷新版面时，这崩的频率相当低了，可以忽略

没有日志，无法修复
