### ISSUE TITLE
跳过开屏广告在新版nga上会多一个toast提示

### ISSUE THREAD

**Issue by forchannot** [chr233/PureNGA#4]
![Screenshot_2023-09-19-23-27-50-145_gov.pianzong.androidnga.jpg](https://github.com/chr233/PureNGA/assets/100580891/5c11dae7-d339-47a6-84bd-492671a2b639)

如图所示，nga版本为9.8.7，模块版本为1.11.0

**Comment by chr233** [comment]
已知问题

**Comment by chr233** [comment]
1.12.0 已解决

**Comment by forchannot** [comment]
更新后变成这种背景色了，有点丑，是预期行为吗，无法改回来![Screenshot_2023-09-21-20-42-46-270_gov.pianzong.androidnga-edit.jpg](https://github.com/chr233/PureNGA/assets/100580891/6bb48df7-c55f-4586-b420-983e1484315e)

![Screenshot_2023-09-21-20-43-02-133_gov.pianzong.androidnga.jpg](https://github.com/chr233/PureNGA/assets/100580891/22a507ed-7540-4a4a-8db9-dd34a1d5e497)

**Comment by chr233** [comment]
1.12.0 有bug，换成1.12.1试试
