### ISSUE TITLE
微信无法分享

### ISSUE THREAD

**Issue by MissingPathfinder** [chr233/PureNGA#6]
用的版本9.9.5和9.9.7，微信分享提示“签名不对”。
![Screenshot_2023-12-02-07-38-54-853_gov pianzong androidnga](https://github.com/chr233/PureNGA/assets/12009221/62163c0d-9bf0-466b-b873-8d76c78069be)

**Comment by chr233** [comment]
重打包会修改应用签名，过不了微信校验正常，这个无解，除非使用完整的xposed框架
