### ISSUE TITLE
9.9.7和9.9.8版本无法保存图片

### ISSUE THREAD

**Issue by joker9527-x** [chr233/PureNGA#7]
之前使用9.9.5整合版本，华为harmonyos系统能保存图片，后续下载9.9.7和9.9.8整合版本安装后，除了不可保存图片，其他功能正常，为了验证是否为应用问题，下载华为应用市场官方发布最新版本（9.9.6），安装后试用，保存图片功能正常，nga隐私管理下有个系统权限管理，只有图片储存功能在purenga整合版本和官方版本都不可设置，不晓得是不是该项设置问题，如果大家想用purenga，可以试试回退到9.9.5版本，以上。
感谢chr233老哥无私开发分享。

**Comment by chr233** [comment]
插件是什么版本，1.17.0 + 9.9.x 还是 1.18.0 + 9.9.x

**Comment by chr233** [comment]
整合版好像可以降级安装的，你可以试试别的版本，或者自己下一个lspatch自己打包，nga历史版本在网盘里有

**Comment by joker9527-x** [comment]
> 插件是什么版本，1.17.0 + 9.9.x 还是 1.18.0 + 9.9.x

1.17.0和1.18.0整合版都试过，两版在9.9.5版本以上均不能保存图片，老哥你提到重新打包lspatch我试试看。

**Comment by chr233** [comment]
> Refer

https://github.com/LSPosed/LSPatch/releases/tag/v0.6

**Comment by chr233** [comment]
试试 9.9.9 ，可能是原版的问题

**Comment by joker9527-x** [comment]
> 试试 9.9.9 ，可能是原版的问题

老哥，抱歉，前段时间又被病魔干趴下啦，咳嗽没完，养了一段时间病，没来得及登录回复你，非常抱歉，今天下载整合版本9.9.14-1.18.0-lspatched.apk，试着保存图片，显示已保存，查看手机库存，能见着picture/nga下确实存在图片，有劳老哥啦，谢谢。
祝您身体健康，新年快乐。

**Comment by chr233** [comment]
那应该就是nga自己的问题了
