### ISSUE TITLE
使用了2.0.0的整合版点进任意一个界面再返回有明显卡顿

### ISSUE THREAD

**Issue by YizeNE** [chr233/PureNGA#9]
只测试了9.9.10和9.9.17两个整合版本，不清楚是nga本身的问题还是模块的问题

**Comment by chr233** [comment]
建议用 9.9.16，以及具体是什么机型会有这种问题

**Comment by chr233** [comment]
> > 建议用 9.9.16，以及具体是什么机型会有这种问题
> 
> 9.9.16依然存在该问题，手机是小米8，用的MIUI 11.0.4

打开了哪些功能呢

**Comment by chr233** [comment]
> > > > 建议用 9.9.16，以及具体是什么机型会有这种问题
> > > 
> > > 
> > > 9.9.16依然存在该问题，手机是小米8，用的MIUI 11.0.4
> > 
> > 打开了哪些功能呢
> 
> 净化设置和界面优化全打开了，然后就是阻止更新和静默运行，9.9.5+1.18.0的整合版没这问题

有没有打开日志功能，我测了下也没有卡顿的问题，只有冷启动会慢一点

**Comment by chr233** [comment]
> > > > > > > > 建议用 9.9.16，以及具体是什么机型会有这种问题
> > > > > > > 
> > > > > > > 
> > > > > > > 9.9.16依然存在该问题，手机是小米8，用的MIUI 11.0.4
> > > > > > 
> > > > > > 
> > > > > > 打开了哪些功能呢
> > > > > 
> > > > > 
> > > > > 净化设置和界面优化全打开了，然后就是阻止更新和静默运行，9.9.5+1.18.0的整合版没这问题
> > > > 
> > > > 
> > > > 有没有打开日志功能，我测了下也没有卡顿的问题，只有冷启动会慢一点
> > > 
> > > 
> > > 没有打开
> > 
> > 
> > 具体是访问什么页面会有卡顿呢，我测试没有这种问题
> 
> 设置，帖子，板块，能点的都卡，没有过渡动画，点进去的时候也会稍微卡顿下，只不过没有返回那么明显，返回是要卡上几秒才能返回

感觉像是lspatch的问题，试试用旧版lspatch打包呢 https://github.com/LSPosed/LSPatch/releases/tag/v0.5.1
1.18.0用的是0.5.1的lspatch，2.0.0升级成0.6了

**Comment by chr233** [comment]
> > > > > > > > > > 建议用 9.9.16，以及具体是什么机型会有这种问题
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 9.9.16依然存在该问题，手机是小米8，用的MIUI 11.0.4
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 打开了哪些功能呢
> > > > > > > 
> > > > > > > 
> > > > > > > 净化设置和界面优化全打开了，然后就是阻止更新和静默运行，9.9.5+1.18.0的整合版没这问题
> > > > > > 
> > > > > > 
> > > > > > 有没有打开日志功能，我测了下也没有卡顿的问题，只有冷启动会慢一点
> > > > > 
> > > > > 
> > > > > 没有打开
> > > > 
> > > > 
> > > > 具体是访问什么页面会有卡顿呢，我测试没有这种问题
> > > 
> > > 
> > > 设置，帖子，板块，能点的都卡，没有过渡动画，点进去的时候也会稍微卡顿下，只不过没有返回那么明显，返回是要卡上几秒才能返回
> > 
> > 感觉像是lspatch的问题，试试用旧版lspatch打包呢 https://github.com/LSPosed/LSPatch/releases/tag/v0.5.1 1.18.0用的是0.5.1的lspatch，2.0.0升级成0.6了
> 
> 不会用这个。。。，电脑上报这错Exception in thread "main" java.lang.UnsupportedClassVersionError: org/lsposed/patch/LSPatch has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0，不知道是不是java版本低了，手机上没有shizuku

不用shizuku，选内置xposed框架，然后默认签名就行
